version: '3'
services:
  # MySQL database
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: lincy
      MYSQL_DATABASE: dairy_mgmt
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Your Tomcat-based microservice
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    
      
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dairy_mgmt
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8762/eureka/  # Updated port to 8763
    volumes:
      - ./target:/usr/local/tomcat/webapps
    networks:
      - eureka-network
      

networks:
  eureka-network:
    external: true  # Use the existing network created in the Eureka Docker Compose
  # dairy-mgmt-frontend:
  #   external: true
volumes:
  mysql_data:
